language: php

dist: precise

php: 
  - 7.1
  - 7.3
  
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - php composer.phar require "phpunit/phpunit:~6"

script: 
  - ./vendor/bin/phpunit
